### ISSUE TITLE
Fuzzing outside the standard library?

### ISSUE THREAD

**Issue by ianprime0509** [squeek502/zig-std-lib-fuzzing#8]
Thanks for creating this project, it's pretty cool to see how many issues can be found with this approach that might not easily be discovered otherwise.

One of my long overdue self-TODOs has been to get fuzzing set up for some of my Zig contributions, which might help find more issues like [this one](https://github.com/ziglang/zig/pull/19577#discussion_r1555161741). However, this code is outside the standard library.

I've taken the approach of accepting a `zig-src` build option to point to a Zig source checkout and used that to add some basic fuzzers for Markdown parsing and Git packfile indexing: https://github.com/ianprime0509/zig-std-lib-fuzzing/tree/non-std-fuzzers I haven't run them for very long yet, but I'm hoping to run them more to see if I can find any other interesting bugs.

Although the declared scope of this project is the Zig standard library, would fuzzers for other stuff in the Zig project be a useful addition?

**Comment by squeek502** [comment]
I like the idea--it's definitely in the spirit of why this repo was made. Feel free to PR those fuzzers if you'd like.

**Comment by ianprime0509** [comment]
Thanks! I opened #9
